"""Generate the three standards documents from committed evidence files.

docs/model-card.md, docs/change-control-plan.md and docs/standards-alignment.md are written by
this script; every number in them is read from a file under results/ (named next to it), never
typed by hand. Edit the wording here and rerun; do not edit the numbers in the documents.

Usage: python scripts/build_docs.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

R = Path("results/phase2")
DOCS = Path("docs")
CHECKED = "2026-10-05"
PCCP = (
    "FDA's final guidance \"Marketing Submission Recommendations for a Predetermined Change "
    'Control Plan for Artificial Intelligence-Enabled Device Software Functions" (December 2024)'
)
NOTICE = (
    "> **{what}.** Structured after, not compliant with, {standard}. This model is a research "
    "prototype and **is not for clinical use**: it must not be used to diagnose, screen or triage "
    "patients. Numbers are generated by `scripts/build_docs.py` from committed evidence files "
    "(named beside each number) and are not edited by hand."
)


def load(path: str) -> Any:
    return json.loads((R / path).read_text(encoding="utf-8"))


def pct(x: float | None, digits: int = 1) -> str:
    return "n/a" if x is None else f"{100 * x:.{digits}f}%"


def rng(s: dict[str, float]) -> str:
    return f"{pct(s['mean'])} (range {pct(s['min'])}–{pct(s['max'])})"


def ci(b: dict[str, Any], key: str) -> str:
    return f"[{pct(b[key]['low'])}, {pct(b[key]['high'])}]"


TEST = load("v2/test/final_test.json")
FULL, V1VIEW = TEST["views"]["test_full_v2"], TEST["views"]["test_v1_images"]
ENS = FULL["ensemble_3_seeds"]
SINGLE = FULL["single_model_over_seeds"]
DRIFT = load("drift/v2/table.json")
TRIAGE = load("triage/test.json")
THRESH = load("triage/threshold.json")
ENS_KEY = "v2-ensemble-final-seeds0-1-2"
TRI = TRIAGE["models"][ENS_KEY]
DATA = load("v2/training/data_summary.json")
BORDERS = load("drift/borders.json")
PROV = load("label_provenance/label_provenance.json")["by_site_and_class"]
DECISION = load("v2/decision.json")
V1TEST = load("overnight/final_test.json")
SHIFT_NAMES = {"buenos_aires": "Buenos Aires", "pad_ufes": "PAD-UFES-20",
               "pathmnist_eval": "PathMNIST", "cifar10_eval": "CIFAR-10"}  # fmt: skip
CLIENTS = ("ham_vienna", "ham_queensland", "barcelona", "msk")
CLIENT_NAMES = {"ham_vienna": "HAM10000 Vienna", "ham_queensland": "HAM10000 Queensland",
                "barcelona": "Barcelona", "msk": "MSK"}  # fmt: skip


def internal_table() -> str:
    p, b = ENS["scores"]["pooled"], ENS["bootstrap_95"]
    rows = [
        "| Model | Balanced accuracy | Macro AUROC | Melanoma sensitivity |",
        "| --- | --- | --- | --- |",
        f"| 3-seed ensemble (shipped) | {pct(p['balanced_accuracy'])} {ci(b, 'balanced_accuracy')} "
        f"| {pct(p['macro_auroc'])} {ci(b, 'macro_auroc')} "
        f"| {pct(p['melanoma_sensitivity'])} {ci(b, 'melanoma_sensitivity')} |",
        f"| Single model, mean of 3 seeds | {rng(SINGLE['balanced_accuracy'])} "
        f"| {rng(SINGLE['macro_auroc'])} | {rng(SINGLE['melanoma_sensitivity'])} |",
    ]
    return "\n".join(rows)


def per_client() -> str:
    s = ENS["scores"]
    rows = ["| Client | Test images | Balanced accuracy (ensemble) |", "| --- | ---: | --- |"]
    rows += [f"| {CLIENT_NAMES[c]} | {s[c]['images']:,} | {pct(s[c]['balanced_accuracy'])} |"
             for c in CLIENTS]  # fmt: skip
    rows += [f"| Barcelona, bordered images | {s['barcelona_bordered']['images']:,} | "
             f"{pct(s['barcelona_bordered']['balanced_accuracy'])} |",
             f"| Barcelona, not bordered | {s['barcelona_not_bordered']['images']:,} | "
             f"{pct(s['barcelona_not_bordered']['balanced_accuracy'])} |"]  # fmt: skip
    return "\n".join(rows)


def triage_table() -> str:
    names = [("Client test, pooled", "client_test_pooled"),
             ("Buenos Aires (external)", "external_buenos_aires"),
             ("PAD-UFES-20 (external)", "external_pad_ufes")]  # fmt: skip
    rows = ["| Group | Images | Melanomas | Specificity | Melanoma sensitivity | Referral rate |",
            "| --- | ---: | ---: | --- | --- | ---: |"]  # fmt: skip
    for label, g in names:
        m = TRI[g]
        rows.append(f"| {label} | {m['images']:,} | {m['melanoma_images']} | "
                    f"{pct(m['specificity'])} {ci(m['bootstrap_95'], 'specificity')} | "
                    f"{pct(m['sensitivity'])} {ci(m['bootstrap_95'], 'sensitivity')} | "
                    f"{pct(m['referral_rate'])} |")  # fmt: skip
    return "\n".join(rows)


def drift_table() -> str:
    c = DRIFT["table"]["centralized"]
    rows = ["| Detector | " + " | ".join(SHIFT_NAMES.values()) + " |",
            "| --- | --- | --- | --- | --- |"]  # fmt: skip
    for det, name in (("mahalanobis", "Mahalanobis (shipped)"), ("gram", "Gram"),
                      ("energy", "Energy"), ("max_softmax", "Max softmax")):  # fmt: skip
        rows.append(f"| {name} | " + " | ".join(
            f"{pct(c[det][s]['auroc']['mean'])} AUROC, {pct(c[det][s]['fpr95']['mean'])} FPR@95"
            for s in SHIFT_NAMES) + " |")  # fmt: skip
    return "\n".join(rows)


def gap_text() -> str:
    """Validation minus test balanced accuracy per model, from the test look's own record."""
    central = [e["val_pooled"]["balanced_accuracy"] - e["scores"]["pooled"]["balanced_accuracy"]
               for e in FULL["single_model_per_seed"]]  # fmt: skip
    e = FULL["ensemble_3_seeds"]
    ens = e["val_pooled"]["balanced_accuracy"] - e["scores"]["pooled"]["balanced_accuracy"]
    fed = {m: [x["val_pooled"]["balanced_accuracy"] - x["scores"]["pooled"]["balanced_accuracy"]
               for x in FULL["federated"][m]["per_seed"]] for m in ("fedavg", "fedprox")}  # fmt: skip
    higher = sum(d < 0 for v in fed.values() for d in v)
    return (f"{100 * min(central):.1f} to {100 * max(central):.1f} points lower on test than on "
            f"validation for the centralized single models and {100 * ens:.1f} points lower for "
            f"the ensemble; for the six federated models it is mixed ({higher} of 6 score higher "
            f"on test)")  # fmt: skip


def provenance_line() -> str:
    return ", ".join(f"{n} {pct(PROV[s]['all']['histopathology_share'])}" for s, n in
                     (("msk", "MSK"), ("barcelona", "Barcelona"), ("buenos_aires", "Buenos Aires"),
                      ("pad_ufes", "PAD-UFES-20"), ("ham10000", "HAM10000")))  # fmt: skip


def model_card() -> str:
    cal = ENS["calibration"]
    ship = DRIFT["ship_rule"]
    pooled_t, ba_t, pad_t = (TRI[g] for g in ("client_test_pooled", "external_buenos_aires",
                                               "external_pad_ufes"))  # fmt: skip
    share = DATA["train_share_by_client"]
    prov_ba = PROV["buenos_aires"]["all"]["by_method"].get("not recorded", 0)
    return f"""# Model card: skin lesion classifier with a drift score (v2)

{NOTICE.format(what="Model card", standard="the CHAI Applied Model Card (mc-schema v0.2)")}

Sections follow the order of CHAI's Applied Model Card v0.2 schema
(github.com/coalition-for-health-ai/mc-schema, `v0.2/schema.xsd`). A crosswalk to the nine
categories of HTI-1 predictive decision support intervention source attributes and to HTI-1's
risk areas is at the end.

## 1. Basic info
- **Model name:** Clinical Imaging Drift Monitor skin lesion classifier, v2: a 3-seed ensemble of
  EfficientNet-B0 models, with a Mahalanobis out-of-distribution (drift) score.
- **Model developer:** Erjon Brucaj (personal portfolio project, solo work).
- **Developer contact:** issues on the project's GitHub repository (erjonb19/clinical-drift-monitor).

## 2. Release info
- **Release stage:** research prototype; not released, not deployed. Serving (Phase 3) is not
  built yet.
- **Release date / version:** not released; evaluated models are the v2 checkpoints recorded in
  `results/phase2/v2/training/final_models.json`.
- **Global availability:** none. **EHR compatibility:** none. **Regulatory approval:** none.

## 3. Model summary
Classifies a dermoscopic image of a skin lesion into seven HAM10000 classes (akiec, bcc, bkl,
df, mel, nv, vasc) and returns a Mahalanobis distance that flags images unlike the training
data. Its purpose in this project is to demonstrate drift monitoring: detecting when the model
sees data it was not built for. **Keywords:** dermoscopy, skin lesion classification,
out-of-distribution detection, drift monitoring, federated learning, research prototype.

## 4. Uses and directions
- **Intended use and workflow:** a research and engineering demonstration of monitoring a
  medical-imaging classifier for site and acquisition drift. No clinical workflow.
- **Primary intended users:** ML and MLOps engineers, and reviewers of this portfolio project.
- **How to use:** offline evaluation from the repository's notebooks and scripts; a serving API
  is planned (Phase 3) and is a stated gap.
- **Targeted patient population:** none clinically. The data are dermoscopic images from the
  four client sources (HAM10000 Vienna and Queensland, Barcelona, MSK).
- **Cautioned out-of-scope settings:** any diagnosis, screening, triage or referral of real
  patients; clinical (non-dermoscopic) photographs, including smartphone photos; primary care or
  other low-prevalence settings; darker skin types (Fitzpatrick IV to VI are barely represented;
  skin type is recorded only at the two held-out sites); lesion classes outside the seven.

## 5. Warnings
**Known risks and limitations**
- **Sensitivity falls at new sites.** At a threshold set on validation for 95% melanoma
  sensitivity, the ensemble's sensitivity is {pct(pooled_t["sensitivity"])} on the clients' test split but
  {pct(ba_t["sensitivity"])} at Buenos Aires and {pct(pad_t["sensitivity"])} at PAD-UFES-20 (`results/phase2/triage/test.json`).
- **Imaging type is confounded with site.** All client images are dermoscopic; PAD-UFES-20 is
  entirely smartphone clinical close-ups and Buenos Aires is partly clinical images.
- **Label provenance.** Every melanoma label at every site is confirmed by histopathology, so
  sensitivity rests on biopsy-proven labels. Specificity rests partly on benign labels confirmed
  without biopsy (serial imaging, single-image expert consensus, confocal microscopy), especially
  outside MSK. Histopathology share of all labels: {provenance_line()}
  (`results/phase2/label_provenance/label_provenance.json`). {prov_ba} Buenos Aires images have no
  confirmation method recorded (a provenance gap).
- **Bordered images.** {pct(DATA["bordered_share_of_train"])} of training images have dark (vignetted) corners, mostly
  from Barcelona; Buenos Aires is {pct(BORDERS["by_source"]["buenos_aires"]["share"])} bordered (`results/phase2/drift/borders.json`).
- **Validation-to-test gap.** The configuration was chosen on validation across many compared
  variants. On the full v2 sets, balanced accuracy is {gap_text()}.
- **Drift scores depend on hardware.** Mahalanobis scores recomputed on CPU differed from the GPU
  run's by up to about 5% (rank order nearly identical); Gram's normalizer by up to 11.8%. A
  baseline and the batches compared with it must be scored on the same setup
  (`results/phase2/batch_drift/reference-186825054715071/`).
- **Federated results are optimistic.** Federated rounds were selected on pooled validation, which
  a real federated deployment could not see.

**Known biases or ethical considerations:** the four training sources are European, Australian
and US dermatology collections; fairness across skin types is not assessed (a stated gap, PLAN.md
Phase 2). Barcelona is {pct(share["barcelona"])} of training images and therefore also of FedAvg's
aggregation weight.

**Clinical risk level:** not assessed. The model is not for clinical use.

## 6. Trust ingredients
### AI system facts
- **Outcomes and outputs:** seven class probabilities; a Mahalanobis drift score (PCA size by the
  method-D rule, 95% of training-feature variance); for the triage analysis only, a referral
  flag when the melanoma probability is at or above {THRESH["thresholds"][ENS_KEY]:.4f}.
- **Model type:** convolutional neural network (EfficientNet-B0, 224 px, centre view), three seeds
  averaged; class-weighted cross-entropy.
- **Foundation models:** torchvision's ImageNet-pretrained EfficientNet-B0, fine-tuned.
- **Input data source:** ISIC Archive public collections (Barcelona/BCN20000, MSK, Buenos Aires,
  PAD-UFES-20) and HAM10000, each image's licence recorded (`docs/DATA_CARD.md`).
- **Output and input data types:** input: one RGB image (JPEG); output: probabilities and a score.
- **Development data characterization:** {DATA["images"]["train"]:,} training, {DATA["images"]["val"]:,} validation and
  {DATA["images"]["test"]:,} test images, split by lesion; training shares {", ".join(f"{CLIENT_NAMES[c]} {pct(share[c])}" for c in CLIENTS)}
  (`results/phase2/v2/training/data_summary.json`).
- **Bias mitigation approaches:** lesion-level splits (no lesion in two splits, gated); class-
  weighted loss; per-site and bordered/non-bordered reporting. No skin-type mitigation.
- **Ongoing maintenance:** planned in Phase 3 (monthly drift job, retraining with a champion/
  challenger test); not built. A stated gap.
- **Security:** not served yet; no endpoint exists. A stated gap until Phase 3.
- **Transparency:** code, configuration, evidence files and the silent-failure log are public in
  the repository.

### Transparency information
- **Funding source:** none (zero-cost project). **Third-party information:** dataset providers as
  listed in `docs/DATA_CARD.md`. **Stakeholders consulted:** none (no clinicians or patients were
  consulted; a stated gap).

## 7. Key metrics
### Usefulness, usability and efficacy
- **Goal:** classify dermoscopic images into seven classes on held-out lesions.
- **Results (internal, clients' test split, {FULL["test_images"]:,} images, {FULL["test_lesions"]:,} lesions;
  `results/phase2/v2/test/final_test.json`, 95% bootstrap intervals by lesion):**

{internal_table()}

- **Interpretation:** the ensemble is better than any single model; intervals are wide (about ±6
  points), partly because some classes have few test images.
- **Test type:** internal validation on a lesion-level held-out test split, one look per model.
- **Validation process:** configuration chosen on validation only; v2 kept over v1 by a rule set
  in advance (pooled validation balanced accuracy {DECISION["centralized"]["change_points"]["pooled"]:+.2f} points, needed +1.00;
  `results/phase2/v2/decision.json`).

### Fairness and equity
- **Goal:** report performance per site and per acquisition subgroup.
- **Results (ensemble balanced accuracy by client, test):**

{per_client()}

- **Interpretation:** Barcelona, the largest client, is the weakest. Skin type is not assessed.
- **Test type / data:** internal test split, per client.

### Safety and reliability
- **Goal:** know when the model is outside its data, and how its errors move at new sites.
- **Results:** drift detection, centralized models, mean over 3 seeds (`results/phase2/drift/v2/table.json`):

{drift_table()}

  The shipped detector was chosen by a rule fixed in advance (highest mean AUROC on the two real
  sites): Mahalanobis {pct(ship["mahalanobis"]["real_sites_mean_auroc"], 2)} against Gram {pct(ship["gram"]["real_sites_mean_auroc"], 2)}, a near tie within the
  seed spread; Gram has the lower false-alarm rate.

  Triage operating point (triage framing, not a clinical claim; threshold set on validation for
  95% sensitivity; `results/phase2/triage/test.json`). Specificity is the metric that carries
  between settings; the referral rate depends on prevalence (about 18% here) and does not:

{triage_table()}

  Calibration: the ensemble's expected calibration error on test is {pct(cal["ece_before"], 2)}; temperature
  scaling fitted on validation made it worse ({pct(cal["ece_after"], 2)}), so the ensemble is used uncalibrated.
- **External validation:** Buenos Aires and PAD-UFES-20 never contributed to training or model
  choice. Seven-class accuracy at these sites is not computed yet (a stated gap); the external
  results are the triage and drift results above.

## 8. Resources
- **Evaluation references:** `results/phase2/` (all files named above); `docs/phase2-note.md`.
- **Clinical trial:** none. **Peer-reviewed publications:** none. **Reimbursement status:** none.
- **Patient consent or disclosure:** public, de-identified datasets used under their licences;
  no new patient data were collected.

## 9. Bibliography
- CHAI Applied Model Card, mc-schema v0.2 (github.com/coalition-for-health-ai/mc-schema).
- Tschandl et al., The HAM10000 dataset, Scientific Data, 2018.
- Pacheco et al., PAD-UFES-20, Mendeley Data, 2020 (doi:10.17632/zr7vgbcyr2.1).
- Lee et al., A simple unified framework for detecting out-of-distribution samples, NeurIPS 2018.
- Sastry and Oore, Detecting out-of-distribution examples with Gram matrices, ICML 2020.

## HTI-1 crosswalk
HTI-1 (ONC, 45 CFR 170.315(b)(11)) lists source attributes for predictive decision support
interventions in nine categories. Status checked {CHECKED}: the requirement is in force; ASTP/ONC's
HTI-5 **proposed** rule (Federal Register document 2025-23896, December 29, 2025) would revise
§170.315(b)(11), including removing these source attributes. No final rule found as of {CHECKED}.
This project is not certified health IT; the categories are used as a structure only.

| HTI-1 source-attribute category | Where in this card |
| --- | --- |
| 1. Details and output of the intervention | 1, 3, 6 (outcomes and outputs) |
| 2. Purpose of the intervention | 3, 4 (intended use) |
| 3. Cautioned out-of-scope use | 4 (cautioned out-of-scope settings), 5 |
| 4. Intervention development details and input features | 6 (model type, input data, development data) |
| 5. Process used to ensure fairness in development | 6 (bias mitigation), 7 (fairness and equity) |
| 6. External validation process | 7 (external validation at Buenos Aires and PAD-UFES-20) |
| 7. Quantitative measures of performance | 7 |
| 8. Ongoing maintenance of implementation and use | 6 (ongoing maintenance): a stated gap until Phase 3 |
| 9. Update and continued validation or fairness assessment schedule | `docs/change-control-plan.md`; schedule is a stated gap until Phase 3 |

| HTI-1 risk area | Evidence or stated gap |
| --- | --- |
| Validity | Internal test with one look per model; external sites; section 7 |
| Reliability | Mean and range over 3 seeds; bootstrap intervals by lesion |
| Robustness | Drift detection and the sensitivity drop at new sites; hardware dependence of scores |
| Fairness | Per-site and bordered results; skin type not assessed (gap) |
| Intelligibility | Not addressed (no explanations); a stated gap |
| Safety | Not for clinical use; triage framing only; risks in section 5 |
| Security | Not served; a stated gap until Phase 3 |
| Privacy | Public de-identified data only; no patient data collected |
"""


def change_control() -> str:
    d = DECISION["centralized"]
    c1, c2 = V1TEST["single_model_over_seeds"], V1VIEW["single_model_over_seeds"]
    f1 = V1TEST["federated"]["fedavg"]["over_seeds"]
    f2 = V1VIEW["federated"]["fedavg"]["over_seeds"]
    notice = NOTICE.format(what="Change-control plan", standard=PCCP)
    return f"""# Change-control plan

{notice}

This is a portfolio exercise, not a regulatory submission. It follows the guidance's three
parts: a description of modifications, a modification protocol, and an impact assessment.

## 1. Description of modifications
Modifications this plan allows, each only through the protocol in section 2:
1. **Retraining with more data from existing sites**, with the same architecture, configuration
   and seeds (done once: v2 raised Barcelona's cap from 5,000 to 10,000 images).
2. **Retraining with a new site's data**, once its labels are released, under the same protocol.
3. **Refitting the drift detector** (Mahalanobis, PCA size by method D) after a retraining.
4. **Site-level recalibration of the triage threshold** (evidence pending: the Buenos Aires
   simulation in PLAN.md, Phase 2).

Not allowed without a new plan: a different architecture or image size, new classes, a new
imaging modality (clinical photographs), or a change to the decision rules in section 2.
Triggers: a confirmed drift alarm from the monthly job, or newly released labels (Phase 3; the
monitoring job is not built yet, a stated gap).

## 2. Modification protocol
- **Data management.** Splits are by lesion. Earlier lesions keep their split when data are added
  (`config/splits_v1.csv`, pipeline gate `frozen_splits_kept`); only new lesions are assigned;
  HAM10000's split fingerprint is gated. Every image's licence is recorded.
- **Retraining.** The approved configuration, three seeds, the same code path, with each run's
  checkpoint and validation result saved as it finishes.
- **Performance evaluation, decided on validation before any test look.** The candidate replaces
  the current model only if pooled validation balanced accuracy rises by at least 1 point and no
  client's falls by more than 3 points, measured on the current model's exact validation images
  (mean of 3 seeds). Applied once so far (`results/phase2/v2/decision.json`): pooled
  {d["change_points"]["pooled"]:+.2f} points, worst client {d["worst_client_change_points"]:+.2f}; v2 was kept.
- **Test.** One look per model, enforced by a lock that records "started" and then "completed";
  reported on the current model's exact test images, with the full new test set as a second row.
- **Drift detector.** Refit on the new training data; the detector choice is not reopened by a
  retraining. Baselines and monitored batches must be scored on the same hardware and settings.
- **Update and rollback.** Champion/challenger in the Unity Catalog model registry with the
  previous version kept for rollback (Phase 3; a stated gap).

## 3. Impact assessment
The one modification made so far, v2 (Barcelona 5,000 to 10,000 images), on v1's exact test images
(`results/phase2/overnight/final_test.json`, `results/phase2/v2/test/final_test.json`):
- Centralized single model, balanced accuracy: {rng(c1["balanced_accuracy"])} to {rng(c2["balanced_accuracy"])}.
- FedAvg, balanced accuracy: {rng(f1["balanced_accuracy"])} to {rng(f2["balanced_accuracy"])}; the gap between centralized and
  federated training widened.
- Risks the protocol does not remove: lower sensitivity at new sites; labels confirmed without
  biopsy behind part of specificity; acquisition (imaging type) differences; hardware-dependent
  drift scores. Each is listed in `docs/model-card.md`, section 5.
"""


def standards() -> str:
    gmlp = [
        (
            "Multi-disciplinary expertise is leveraged throughout the total product life cycle",
            "Gap: a solo project; no clinical or regulatory reviewers.",
        ),
        (
            "Good software engineering and security practices are implemented",
            "Typed code, tests and CI on every push; small commits; gates in the pipeline; "
            "`docs/silent-failures.md`. Security: gap until serving exists.",
        ),
        (
            "Clinical study participants and data sets are representative of the intended patient population",
            "Partial: four clients and two held-out sites, per-site reporting; skin types IV to VI "
            "barely represented (gap).",
        ),
        (
            "Training data sets are independent of test sets",
            "Lesion-level splits, gated (no lesion in two splits; frozen v1 splits); held-out sites "
            "never used in training or model choice.",
        ),
        (
            "Selected reference datasets are based upon best available methods",
            "Partial: melanoma labels all histopathology-confirmed; benign labels partly confirmed "
            "without biopsy (`results/phase2/label_provenance/label_provenance.json`).",
        ),
        (
            "Model design is tailored to the available data and reflects the intended use of the device",
            "Configuration chosen on validation by a pre-set rule; no clinical intended use (gap).",
        ),
        (
            "Focus is placed on the performance of the human-AI team",
            "Gap: no reader or human-in-the-loop study.",
        ),
        (
            "Testing demonstrates device performance during clinically relevant conditions",
            "Partial: external sites and a triage operating point; no prospective or clinical "
            "testing (gap).",
        ),
        ("Users are provided clear, essential information", "`docs/model-card.md`."),
        (
            "Deployed models are monitored for performance and re-training risks are managed",
            "Partial: drift detection measured in Phase 2; `docs/change-control-plan.md`; the "
            "monitoring job is Phase 3 (gap).",
        ),
    ]
    tripod = [
        ("Title", "Gap: no manuscript; the README and model card name the model and task."),
        ("Abstract", "Gap: no manuscript."),
        ("Background", "PLAN.md, opening sections."),
        ("Objectives", "PLAN.md (each phase's goal and 'Done when')."),
        ("Data", "`docs/DATA_CARD.md`, `config/sites.json`."),
        ("Participants", "`docs/DATA_CARD.md`; images, not patients, are the unit (a limitation)."),
        ("Data preparation", "`config/sites.json` (silver format); `pipelines/lakehouse.py`."),
        ("Outcome", "Seven HAM10000 classes; site label rule for 'SCC, NOS' (PLAN.md)."),
        ("Predictors", "The image only; no clinical predictors."),
        (
            "Sample size",
            "Partial: counts reported per split, class and site; no sample-size calculation.",
        ),
        ("Missing data", "Unlabelled images are scoring-only; failed decodes quarantined (gated)."),
        ("Analytical methods", "`src/cdm/` (training, OOD, evaluation); `docs/phase2-note.md`."),
        ("Class imbalance", "Class-weighted loss; balanced accuracy as the main metric."),
        ("Fairness", "Per-site and bordered reporting; skin type not assessed (gap)."),
        ("Model output", "Class probabilities and a drift score (model card, section 6)."),
        (
            "Training versus evaluation",
            "Lesion-level splits; one test look per model; held-out sites.",
        ),
        ("Ethical approval", "Not applicable: public de-identified data; stated."),
        ("Open science", "Code public; no protocol registration (gap); data from public archives."),
        ("Patient and public involvement", "Gap: none."),
        ("Participants (results)", "Counts in `results/phase2/v2/training/data_summary.json`."),
        ("Model development", "`results/phase2/ladder/`, `results/phase2/v2/training/`."),
        (
            "Model specification",
            "Configuration and checkpoints' weight hashes in the result files.",
        ),
        (
            "Model performance",
            "`results/phase2/v2/test/final_test.json`, drift and triage results.",
        ),
        ("Model updating", "v1 to v2 (`results/phase2/v2/decision.json`)."),
        ("Interpretation", "`docs/phase2-note.md`."),
        ("Limitations", "Model card, section 5; `docs/silent-failures.md`."),
        ("Usability of the model in the context of current care", "Gap: not for clinical use."),
    ]
    imdrf = [
        (
            "Valid clinical association",
            "Gap: no association argument beyond published dermoscopy "
            "practice; the model is a research prototype.",
        ),
        (
            "Analytical validation",
            "Internal test (one look per model), seeds, bootstrap intervals, "
            "calibration, reproducibility checks (`docs/silent-failures.md`).",
        ),
        (
            "Clinical validation",
            "Gap: external site results only (Buenos Aires, PAD-UFES-20); no clinical study.",
        ),
    ]
    rows_g = "\n".join(f"| {i} | {p} | {e} |" for i, (p, e) in enumerate(gmlp, 1))
    rows_t = "\n".join(f"| {i} | {p} | {e} |" for i, (p, e) in enumerate(tripod, 1))
    rows_i = "\n".join(f"| {p} | {e} |" for p, e in imdrf)
    return f"""# Standards alignment

{NOTICE.format(what="Standards alignment", standard="the GMLP guiding principles, TRIPOD+AI and the IMDRF SaMD clinical evaluation framework")}

Each item is mapped to evidence in this repository or to a stated gap.

## Good Machine Learning Practice: 10 guiding principles (FDA, Health Canada, MHRA, 2021)
| # | Principle | Evidence or gap |
| --- | --- | --- |
{rows_g}

## TRIPOD+AI: 27 items (Collins et al., BMJ, 2024)
| # | Item | Evidence or gap |
| --- | --- | --- |
{rows_t}

## IMDRF SaMD clinical evaluation: three pillars (IMDRF/SaMD WG/N41, 2017)
| Pillar | Evidence or gap |
| --- | --- |
{rows_i}
"""


def main() -> None:
    for name, text in (("model-card.md", model_card()), ("change-control-plan.md", change_control()),
                       ("standards-alignment.md", standards())):  # fmt: skip
        (DOCS / name).write_text(text, encoding="utf-8", newline="\n")
        print("wrote", DOCS / name)


if __name__ == "__main__":
    main()
